---
title: "what US presidents say in inaugural speeches"
output: html_notebook
---

load libraries:
```{r}
packages.used=c("tm", "wordcloud", "RColorBrewer", 
                "dplyr", "tidytext")

# check packages that need to be installed.
packages.needed=setdiff(packages.used, 
                        intersect(installed.packages()[,1], 
                                  packages.used))
# install additional packages
if(length(packages.needed)>0){
  install.packages(packages.needed, dependencies = TRUE,
                   repos='http://cran.us.r-project.org')
}

library(tm)
library(wordcloud)
library(RColorBrewer)
library(dplyr)
library(tidytext)

packages.used=c("rvest", "tibble", "qdap", 
                "sentimentr", "gplots", "dplyr",
                "tm", "syuzhet", "factoextra", 
                "beeswarm", "scales", "RColorBrewer",
                "RANN", "tm", "topicmodels")

# check packages that need to be installed.
packages.needed=setdiff(packages.used, 
                        intersect(installed.packages()[,1], 
                                  packages.used))
# install additional packages
if(length(packages.needed)>0){
  install.packages(packages.needed, dependencies = TRUE)
}

# load packages
library("rvest")
library("tibble")
library("qdap")
library("sentimentr")
library("gplots")
library("dplyr")
library("tm")
library("syuzhet")
library("factoextra")
library("beeswarm")
library("scales")
library("RColorBrewer")
library("RANN")
library("tm")
library("topicmodels")

source("../lib/plotstacked.R")
source("../lib/speechFuncs.R")

```

read all files
```{r}
setwd("./data")
filenames=list.files("InauguralSpeeches",pattern = ".txt",full.names = TRUE)
ldf =sapply(filenames, readChar,nchars=file.info(filenames)$size)
names(ldf)=
```
a proper name for each speech
```{r}
#filenames



name_processing=function(filename,pattern){
  matches=regexec(pattern = pattern,filename)
  result<-regmatches(filename,matches)[[1]][2]
  return(result)
}
regex="inaug(.*?)\\.txt"

filenames_new=list()
for (filename in filenames){
  
  filenames_new=c(filenames_new,name_processing(filename,pattern=regex))
}

names(ldf)=filenames_new

#sapply(filenames,)
```

split whole paragraph into words
```{r}
k=strsplit(ldf$`AbrahamLincoln-1`[1]," ")
sort(table(k),decreasing = TRUE)

```
Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Ctrl+Alt+I*.

When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Ctrl+Shift+K* to preview the HTML file).
